import { useCallback, useEffect, useMemo, useState } from "react";
import { parseSarif, severityOf, type ParsedReport, type Severity } from "./lib/sarif";
import { TopBar } from "./components/TopBar";
import { Headline } from "./components/Headline";
import { Stats } from "./components/Stats";
import { SeverityDonut } from "./components/SeverityDonut";
import { RuleBars } from "./components/RuleBars";
import { Findings } from "./components/Findings";

export default function App() {
  const [report, setReport] = useState<ParsedReport | null>(null);
  const [sevFilter, setSevFilter] = useState<Set<Severity>>(new Set());
  const [query, setQuery] = useState("");
  const [dragging, setDragging] = useState(false);

  useEffect(() => {
    fetch("sample.sarif")
      .then((r) => r.json())
      .then((d) => setReport(parseSarif(d)))
      .catch(() => setReport({ tool: "spring-taint", findings: [] }));
  }, []);

  const loadFile = useCallback((file: File) => {
    file
      .text()
      .then((t) => setReport(parseSarif(JSON.parse(t))))
      .catch((e) => alert("Could not parse SARIF: " + e.message));
  }, []);

  // drag & drop anywhere
  useEffect(() => {
    let depth = 0;
    const enter = (e: DragEvent) => { e.preventDefault(); if (++depth === 1) setDragging(true); };
    const over = (e: DragEvent) => e.preventDefault();
    const leave = (e: DragEvent) => { e.preventDefault(); if (--depth <= 0) { depth = 0; setDragging(false); } };
    const drop = (e: DragEvent) => {
      e.preventDefault(); depth = 0; setDragging(false);
      const f = e.dataTransfer?.files?.[0]; if (f) loadFile(f);
    };
    window.addEventListener("dragenter", enter);
    window.addEventListener("dragover", over);
    window.addEventListener("dragleave", leave);
    window.addEventListener("drop", drop);
    return () => {
      window.removeEventListener("dragenter", enter);
      window.removeEventListener("dragover", over);
      window.removeEventListener("dragleave", leave);
      window.removeEventListener("drop", drop);
    };
  }, [loadFile]);

  const stats = useMemo(() => {
    const sevCount: Record<Severity, number> = { critical: 0, high: 0, medium: 0, low: 0 };
    const ruleCount: Record<string, number> = {};
    const ruleSeverity: Record<string, Severity> = {};
    const files = new Set<string>();
    for (const f of report?.findings ?? []) {
      sevCount[f.severity]++;
      ruleCount[f.ruleId] = (ruleCount[f.ruleId] ?? 0) + 1;
      ruleSeverity[f.ruleId] = f.severity;
      files.add(f.file);
    }
    return { sevCount, ruleCount, ruleSeverity, files: files.size, rules: Object.keys(ruleCount).length };
  }, [report]);

  const filtered = useMemo(() => {
    const q = query.toLowerCase();
    return (report?.findings ?? []).filter(
      (f) =>
        (sevFilter.size === 0 || sevFilter.has(f.severity)) &&
        (!q || `${f.ruleId} ${f.file} ${f.message}`.toLowerCase().includes(q)),
    );
  }, [report, sevFilter, query]);

  const toggleSev = (s: Severity) =>
    setSevFilter((prev) => {
      const next = new Set(prev);
      next.has(s) ? next.delete(s) : next.add(s);
      return next;
    });

  const total = report?.findings.length ?? 0;

  return (
    <>
      <div className="grain" aria-hidden />
      <div className="glow" aria-hidden />

      <TopBar tool={report?.tool ?? "—"} files={stats.files} rules={stats.rules} onFile={loadFile} />

      <main className="wrap">
        <Headline total={total} files={stats.files} sevCount={stats.sevCount} />
        <Stats total={total} sevCount={stats.sevCount} files={stats.files} rules={stats.rules} />

        <section className="panels">
          <SeverityDonut sevCount={stats.sevCount} total={total} />
          <RuleBars ruleCount={stats.ruleCount} severityOf={(r) => stats.ruleSeverity[r] ?? severityOf(r)} />
        </section>

        <Findings
          findings={filtered}
          sevCount={stats.sevCount}
          sevFilter={sevFilter}
          toggleSev={toggleSev}
          query={query}
          setQuery={setQuery}
        />
      </main>

      <footer className="foot">
        <span>
          Generated by{" "}
          <a href="https://github.com/GabrielBBaldez/spring-taint" target="_blank" rel="noopener noreferrer">
            spring-taint
          </a>{" "}
          · SARIF 2.1
        </span>
        <span className="foot-tag">
          drop a <code>.sarif</code> file anywhere to load it
        </span>
      </footer>

      {dragging && (
        <div className="dropzone">
          <div className="dropzone-inner">release to load SARIF</div>
        </div>
      )}
    </>
  );
}
